// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBSDORQ6awR7O5ZEPbucml6x9hAQ0JNpUE',
    appId: '1:856093190880:web:b9e4eaae9809657f61be85',
    messagingSenderId: '856093190880',
    projectId: 'android-flutter-fruit',
    authDomain: 'android-flutter-fruit.firebaseapp.com',
    storageBucket: 'android-flutter-fruit.firebasestorage.app',
    measurementId: 'G-6DXWD5K0LS',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBtKwJox2Egcl5qJYTQ0SvzsQy7NXM8eFg',
    appId: '1:856093190880:android:8adc15dc5fb67a0661be85',
    messagingSenderId: '856093190880',
    projectId: 'android-flutter-fruit',
    storageBucket: 'android-flutter-fruit.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCUyS6qkCd8kL6cifXDlNWo7bfXcSGWwr4',
    appId: '1:856093190880:ios:6d8d32d1d3a8388361be85',
    messagingSenderId: '856093190880',
    projectId: 'android-flutter-fruit',
    storageBucket: 'android-flutter-fruit.firebasestorage.app',
    iosBundleId: 'com.example.froutEcomerceApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCUyS6qkCd8kL6cifXDlNWo7bfXcSGWwr4',
    appId: '1:856093190880:ios:6d8d32d1d3a8388361be85',
    messagingSenderId: '856093190880',
    projectId: 'android-flutter-fruit',
    storageBucket: 'android-flutter-fruit.firebasestorage.app',
    iosBundleId: 'com.example.froutEcomerceApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBSDORQ6awR7O5ZEPbucml6x9hAQ0JNpUE',
    appId: '1:856093190880:web:e8b2b30013392e8361be85',
    messagingSenderId: '856093190880',
    projectId: 'android-flutter-fruit',
    authDomain: 'android-flutter-fruit.firebaseapp.com',
    storageBucket: 'android-flutter-fruit.firebasestorage.app',
    measurementId: 'G-0T7JQN8F86',
  );
}
